### ISSUE TITLE
DB selection values not mapped to actual values

### ISSUE THREAD

**Issue by siddygups** [granularai/geometa#8]
We need a table that map integer form question values to their corresponding values.  We also need to load these values from the db rather than hard-code them. 

from https://wtforms.readthedocs.io/en/stable/fields.html:
Select fields with dynamic choice values:
```
class UserDetails(Form):
    group_id = SelectField(u'Group', coerce=int)

def edit_user(request, id):
    user = User.query.get(id)
    form = UserDetails(request.POST, obj=user)
    form.group_id.choices = [(g.id, g.name) for g in Group.query.order_by('name')]
```

**Comment by sagarverma** [comment]
I am assuming this is resolved.
